#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

domainFluid=${PWD}/runData/fluidDomain
domainStructure=${PWD}/runData/structureDomain

# Ranks set to each domain
numProcsFluid=6
numProcsStructure=1

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create and copy data to run folder
./runCtrl/runDataFolderCreation

# Get application name for structure domain
solverStructure=structureDomainRun.py

# Get application name for fluid domain
cd runData/fluidDomain
solverFluid=$(getApplication)
echo application is ${solverFluid}
cd ../../

# Pre-processing
./runCtrl/preProcess

echo -n "ParaSiF running..."

# ParaSiF case with OpenFOAM_MUI(C++)_MUI(python)_FEniCS parallel run
mpirun -np ${numProcsFluid} -wdir ${domainFluid} ${solverFluid} -parallel -coupled :\
       -np ${numProcsStructure} -wdir ${domainStructure} python3 -m mpi4py ${solverStructure}\
        > runData/logFiles/log.foamRun 2>&1 | tail -f runData/logFiles/log.foamRun

echo "Done"

# Post-processing
./runCtrl/postProcess

# ----------------------------------------------------------------- end-of-file